# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f7ea1cad669c6c130a4e209494406a402d9c4fadd4a0adaba0f0615a05083480f48cdb88bf394a9251149de817a31fcace0a3b16ae9b63965d6aefb9011afb8

test:
  secret_key_base: b523e70a84ae1a1acf0cd4c3de26f4d39b57e568f7a8675178c7c6e4f4de99a81b993060ba41dc87e0406e2b0cffe30b0e2ad88c5416a7835a00c4da50baee82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
