CREATE TABLE Course (
	 ID	INTEGER PRIMARY KEY AUTOINCREMENT
	,Name TEXT NOT NULL
	,Department TEXT NOT NULL
);

CREATE TABLE Course_Schedule (
	ID INTEGER PRIMARY KEY AUTOINCREMENT
   ,CourseID INTEGER NOT NULL
   ,WeekdayID INTEGER NOT NULL
   ,HourID INTEGER NOT NULL

   ,UNIQUE (CourseID,WeekdayID,HourID)
   ,FOREIGN KEY(CourseID) REFERENCES Course(ID)
);

CREATE TABLE Student (
	 ID INTEGER PRIMARY KEY AUTOINCREMENT
	,First_Name	TEXT NOT NULL
	,Last_Name TEXT NOT NULL
	UNIQUE (First_Name, Last_Name)
);

CREATE TABLE Enrollment (
	 ID INTEGER PRIMARY KEY AUTOINCREMENT
	,CourseID INTEGER NOT NULL
	,StudentID INTEGER NOT NULL
	
	,UNIQUE (CourseID, StudentID)
	,FOREIGN KEY(CourseID) REFERENCES Course(ID)
	,FOREIGN KEY(StudentID) REFERENCES Student(ID)
);


