# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38f94bece6bdd084256c22a9442fb0fe9c3ac5ddb2e21da83cd33644fa33ecc9d8fbcd1fcab30959c6474886870ace2e7d33ff4cc66bc5525efdd3d7cdda9a19

test:
  secret_key_base: 88f46fa9ec9fad8839e0b14252c24fccca20abcb938849b67c61e677040298526094cf2ae4581d40bd71a09f5c440444edc1816e9738f994c9e7a6f1ccbbe7ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
